/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i orgexampleddbustest_adaptor.h -a :orgexampleddbustest_adaptor.cpp OrgExampleDdbusTest.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "orgexampleddbustest_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class WtestAdaptor
 */

WtestAdaptor::WtestAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

WtestAdaptor::~WtestAdaptor()
{
    // destructor
}

void WtestAdaptor::getValue()
{
    // handle method call org.example.qdbus.wtest.getValue
    QMetaObject::invokeMethod(parent(), "getValue");
}

void WtestAdaptor::setValue(double newValue)
{
    // handle method call org.example.qdbus.wtest.setValue
    QMetaObject::invokeMethod(parent(), "setValue", Q_ARG(double, newValue));
}

