/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a orgexampleddbustest_adaptor.h: OrgExampleDdbusTest.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORGEXAMPLEDDBUSTEST_ADAPTOR_H
#define ORGEXAMPLEDDBUSTEST_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.example.qdbus.wtest
 */
class WtestAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.example.qdbus.wtest")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.example.qdbus.wtest\">\n"
"    <signal name=\"valueChanged\">\n"
"      <arg direction=\"out\" type=\"d\" name=\"newValue\"/>\n"
"    </signal>\n"
"    <method name=\"setValue\">\n"
"      <arg direction=\"in\" type=\"d\" name=\"newValue\"/>\n"
"    </method>\n"
"    <method name=\"getValue\"/>\n"
"  </interface>\n"
        "")
public:
    WtestAdaptor(QObject *parent);
    virtual ~WtestAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void getValue();
    void setValue(double newValue);
Q_SIGNALS: // SIGNALS
    void valueChanged(double newValue);
};

#endif
