/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -p orgexampleddbustest_interface.h: OrgExampleDdbusTest.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef ORGEXAMPLEDDBUSTEST_INTERFACE_H
#define ORGEXAMPLEDDBUSTEST_INTERFACE_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.example.qdbus.wtest
 */
class OrgExampleQdbusWtestInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.example.qdbus.wtest"; }

public:
    OrgExampleQdbusWtestInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = nullptr);

    ~OrgExampleQdbusWtestInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> getValue()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("getValue"), argumentList);
    }

    inline QDBusPendingReply<> setValue(double newValue)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(newValue);
        return asyncCallWithArgumentList(QStringLiteral("setValue"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void valueChanged(double newValue);
};

namespace org {
  namespace example {
    namespace qdbus {
      typedef ::OrgExampleQdbusWtestInterface wtest;
    }
  }
}
#endif
